name: Deploy infraestrutura Amazon RDS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploying using AWS
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2

        # Set up Terraform
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.5.6
  
        # Validate Terraform configuration
        - name: Terraform Validate
          run: terraform validate
  
#         - name: Configure AWS credentials
#           uses: aws-actions/configure-aws-credentials@v1
#           with:
#             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#             aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
#             aws-region: ${{ env.REGION_DEFAULT }}

    
